# -*- coding: utf-8 -*-
"""Fraudulentjobdetectionipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w33-R7M-n2BN3WZUoTfx5WaS9XP-cSYc
"""

import pandas as pd
import numpy as np
import re

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

data=pd.read_csv("fake_job_postings.csv", encoding='latin1', on_bad_lines='skip')
print(data.head())

data = data[['title', 'description', 'fraudulent','salary_range','company_profile','location']].copy()
data['title'] = data['title'].fillna("")
data['description'] = data['description'].fillna("")
data['company_profile'] = data['company_profile'].fillna("")
data['location'] = data['location'].fillna("")
data['salary_range'] = data['salary_range'].fillna("")
data['text'] = data['title'] + " " + data['description']+" "+data['company_profile']+" "+data['location']+" "+data['salary_range']
print(data.head())

#text cleaning
def clean_text(text):
  text=text.lower()
  text=re.sub(r'[^a-zA-Z0-9]'," ",text)
  text=re.sub(r'\s+'," ",text)
  return text
data['text']=data['text'].apply(clean_text)

tokenizer=Tokenizer(num_words=5000)
tokenizer.fit_on_texts(data['text'])
sequences=tokenizer.texts_to_sequences(data['text'])
X=pad_sequences(sequences,maxlen=100)
y=data['fraudulent']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = Sequential()

model.add(Embedding(input_dim=5000, output_dim=64))
model.add(LSTM(64))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

model.fit(X_train, y_train, epochs=5, batch_size=32, validation_data=(X_test, y_test))

y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

def predict_job(text):
    text = clean_text(text)
    seq = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(seq, maxlen=100)

    pred = model.predict(padded)

    if pred > 0.8:
      return("Fake Job")
    elif pred> 0.6:
      return("Suspicious Job")
    else:
      return("Real Job")

print(predict_job("""Job Title: Data Analyst Intern

Company: Insight Analytics Pvt. Ltd.
Location: Work from Home
Duration: 2 Months
Stipend: ₹8,000/month

About the Role:
Insight Analytics is seeking a Data Analyst Intern to assist in analyzing datasets and generating meaningful insights. The intern will work closely with the analytics team on real-world business problems.

Responsibilities:
- Collect, clean, and analyze data from various sources
- Create reports and dashboards using tools like Excel or Power BI
- Assist in identifying trends and patterns in data
- Support the team in data-driven decision-making
- Document findings and present results clearly

Requirements:
- Basic knowledge of Python or SQL
- Familiarity with Excel or data visualization tools
- Understanding of statistics and data analysis concepts
- Good analytical and problem-solving skills
- Strong communication skills

Perks:
- Certificate of completion
- Letter of recommendation
- Flexible working hours
- Opportunity to work on real datasets

Who Can Apply:
- Students available for a work-from-home internship
- Can commit for 2 months
- Have relevant skills and interest in data analysis

About the Company:
Insight Analytics Pvt. Ltd. provides data-driven solutions to businesses across finance, retail, and healthcare sectors."""))

import seaborn as sns
sns.countplot(x='fraudulent', data=data)

data['text_length'] = data['text'].apply(len)

sns.histplot(data[data['fraudulent']==0]['text_length'], label='Real', kde=True)
sns.histplot(data[data['fraudulent']==1]['text_length'], label='Fake', kde=True)